ALTER TABLE "Student"
ADD COLUMN "contact" TEXT NOT NULL DEFAULT 'Not provided';

ALTER TABLE "Student"
ALTER COLUMN "contact" DROP DEFAULT;

ALTER TABLE "Guardian"
ADD COLUMN "email" TEXT,
ADD COLUMN "password" TEXT,
ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX "Guardian_email_key" ON "Guardian"("email");
